library(dplyr)
MechaCar <-  read.csv(file='MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=MechaCar)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=MechaCar))
Sus_coil <-  read.csv(file='Suspension_Coil.csv',check.names=F,stringsAsFactors = F)
total_summary <- Sus_coil %>% summarize(Mean_PSI=mean(PSI), median_PSI=median(PSI), SD_PSI=sd(PSI) )
lot_summary <- Sus_coil %>% group_by(Manufacturing_Lot)%>% summarize(Mean_PSI=mean(PSI), median_PSI=median(PSI), SD_PSI=sd(PSI), .groups = 'keep' )
?t.test()
sample_table <- Sus_coil %>% sample_n(100) 
t.test(log10(sample_table$PSI),mu=mean(log10(Sus_coil$PSI)))